POST http://localhost:8081/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld0BleGFtcGxlLmNvbSIsImV4cCI6MTc2MzQ5ODQ3OCwidXNlcklkIjoyfQ.TqwpmYIR6AoVSo2A5BuvxSVUUQX81dafY8VyqwGKExc

